FROM mcr.microsoft.com/dotnet/sdk:6.0

WORKDIR /src/GrillBot
ENV TZ=Europe/Prague
ENV ASPNETCORE_URLS 'http://+:5000'
ENV DOTNET_PRINT_TELEMETRY_MESSAGE 'false'

RUN sed -i'.bak' 's/$/ contrib/' /etc/apt/sources.list
RUN apt update && apt install -y --no-install-recommends tzdata ttf-mscorefonts-installer fontconfig libc6-dev libgdiplus libx11-dev
RUN ln -s /usr/lib/libgdiplus.so /usr/lib/gdiplus.dll
RUN fc-cache -fv
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

COPY . .
RUN dotnet restore -r linux-x64
RUN dotnet build -c Release --no-restore
RUN dotnet test -v minimal --nologo -l:"console;verbosity=normal" --no-restore
